config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users

  devise_scope :user do
    authenticated do
      root 'schools#dashboard', as: :authenticated_root
    end
    
    root to: "devise/sessions#new"
  end
  
  resources :users, except: :create do
    collection do
      post 'registration'
      post 'create_user'
    end
    member do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :schools do
    member do
      get 'edit_profile'
      post 'update_profile'
    end
  end

  resources :batches do
    collection do
      post 'choose_school'
    end
    member do
      get 'assign_cls_teacher'
      post 'assigned_cls_teacher'
    end 
  end

  resources :school_classes
  resources :class_sections
  resources :admissions
  resources :class_teachers
  resources :exams
  resources :question_papers
  resources :customer_registrations

end

app/models/class_section.rb
class ClassSection < ApplicationRecord

  belongs_to :school_class

  # def get_user_by_role
  #   sections = ""
  #   self.class_sections.each do |sec|
  #     sections = [sections, sec.section_name].join(' ')
  #   end
  #   sections
  # end
  
end

app/controllers/class_sections_controller.rb
class ClassSectionsController < ApplicationController
  layout "dashboard"
  before_action :set_school_class, only: [:index, :new, :create, :destroy, :edit, :update]

  def index
    @class_sections = ClassSection.where(school_class_id: @school_class.id)
  end

  def new
    @class_section = ClassSection.new
  end

  def create
    class_section = ClassSection.new(class_section_params)
    class_section.school_class_id = @school_class.id
    if class_section.save!
      flash[:success] = "Section Added successfully."
    else
      flash[:danger] = "Something went wrong."  
    end
    redirect_to class_sections_path(school_class_id: @school_class.id)
  end

  def destroy
    @class_section = ClassSection.find_by(id: params[:id])
    if @class_section.destroy
      flash[:danger] = "Section has been deleted successfully."
    end
    redirect_to class_sections_path(school_class_id: @school_class.id)
  end

  def edit
    @class_section = ClassSection.find_by(id: params[:id])
  end

  def update
    class_section = ClassSection.find_by(id: params[:id])
    class_section.school_class_id = @school_class.id
    if class_section.update_attributes(class_section_params)
      flash[:success] = " Class Section Sucessfully updated!!"
    else
      flash[:error] = "Sorry! Something went wrong. Please contact support."
    end
    redirect_to class_sections_path(school_class_id: @school_class.id)
  end

  

  private

  def class_section_params
    params.require(:class_section).permit(:section_name, :description, :capacity)
  end

  def set_school_class
    @school_class = SchoolClass.find_by_id(params[:school_class_id])
  end

end

app/helpers/class_sections_helper.rb
module ClassSectionsHelper

end

app/views/class_sections/edit.html.haml
.container#centerwrap
  %h1 Edit Section Details for Section #{@class_section.section_name} of Class #{@class_section.school_class.class_name}
  = form_for @class_section, url: class_section_path(id: @class_section.id, school_class_id: @class_section.school_class_id), method: :put do |f|
    .row
      .form-group.col-sm-8
        = f.label :section_name,'Section Name'
        = f.text_field :section_name, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :description,'Description'
        = f.text_field :description, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :capacity,'Capacity'
        = f.number_field :capacity, class: "form-control"          
    .row
      .col-md-12
        = f.submit "Update Section", class: "btn btn-primary"        

app/views/class_sections/index.html.haml
#centerwrap.container
  .row
    .col-md-10
      %h2{style: "font-weight: bold"} Manage Sections for Class #{@school_class.class_name}
      = link_to new_class_section_path(school_class_id: @school_class.id), class: "btn btn-success", style: "margin-bottom: 10px; float:right;"  do
        %i.glyphicon.glyphicon-plus
        Add Section
      .row
      - @class_sections.each do |class_section|
        .col-sm-4
          .panel.panel-primary.text-center
            .panel-heading
              %div
                %h5
                  Section #{class_section.section_name}
                  %span.badge.badge-light 
                    Strength 
                    %span.badge{style: "background-color: green; color: white;"}
                      #{class_section.capacity}
                %h6.desc_h6= class_section.description
                / .row
                /   .col-sm-6
                /     %h5 Class Teacher: ' '
                /   .col-sm-6
                /     = link_to "(Change)", new_class_teacher_path(class_section_id:class_section.id, school_class_id: @school_class.id),  class: 'btn btn-primary'
            .panel-body 
              = link_to edit_class_section_path(id: class_section.id) do
                %i.glyphicon.glyphicon-pencil.pull-left
              &nbsp;
              = link_to class_section_path(id: class_section.id, school_class_id: class_section.school_class_id), data:{confirm: "Are you sure,you want to delete this Section?"}, method: :delete do
                %i.glyphicon.glyphicon-trash.pull-right

app/views/class_sections/new.html.haml
.container#centerwrap
  %h1 Add New Section
  = form_for @class_section, url: class_sections_path(school_class_id: @school_class.id), method: :post do |f|
    .row
      .form-group.col-sm-8
        = f.label :section_name,'Section Name'
        = f.text_field :section_name, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :description,'Description'
        = f.text_field :description, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :capacity,'Capacity'
        = f.number_field :capacity, class: "form-control"          
    .row
      .col-md-12
        = f.submit "Create Section", class: "btn btn-primary"