config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users

  devise_scope :user do
    authenticated do
      root 'schools#dashboard', as: :authenticated_root
    end
    
    root to: "devise/sessions#new"
  end
  
  resources :users, except: :create do
    collection do
      post 'registration'
      post 'create_user'
    end
    member do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :schools do
    member do
      get 'edit_profile'
      post 'update_profile'
    end
  end

  resources :batches do
    collection do
      post 'choose_school'
    end
    member do
      get 'assign_cls_teacher'
      post 'assigned_cls_teacher'
    end 
  end

  resources :school_classes
  resources :class_sections
  resources :admissions
  resources :class_teachers
  resources :exams
  resources :question_papers
  resources :customer_registrations

end

app/models/batch.rb
class Batch < ApplicationRecord
  has_many :admissions
  has_many :students, through: :admissions
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  layout "dashboard"
  skip_before_action :verify_authenticity_token, only: [:choose_school]

  def index
    @batches = Batch.all
  end

  def new
    @batch = Batch.new
  end

  def create
    batch = Batch.new(batch_params)
    if batch.save!
      flash[:success] = "Batch Added successfully."
    else
      flash[:danger] = "Something went wrong."  
    end
    redirect_to batches_path
  end

  def edit
    @batch = Batch.find_by(id: params[:id])
  end

  def update
    @batch = Batch.find_by(id: params[:id])
    if @batch.update_attributes(batch_params)
    flash[:success] = "Batch Sucessfully updated!!"
    else
      flash[:error] = "Sorry! Something went wrong. Please contact support."
    end
    redirect_to batches_path
  end

  def destroy
    @batch = Batch.find_by(id: params[:id])
    if @batch.destroy
      flash[:danger] = "Batch has been deleted successfully."
    end
    redirect_to batches_path
  end

  def show
    @batch = Batch.find_by(id: params[:id])
    @school_classes = current_user.school.school_classes
  end

  def assign_cls_teacher
    @class_teacher = ClassTeacher.new
    @cls_sec = ClassSection.find_by_id(params[:class_section_id])
    @teachers = current_user.school.users.with_role(:teacher)
  end

  def assigned_cls_teacher
    @class_teacher = ClassTeacher.new(class_teacher_params)
    @class_teacher.batch_id = params[:id]
    if @class_teacher.save!
      flash[:success] = "Sucessfully added Class Teacher !!"
    else
      flash[:error] = "Sorry! Something went wrong. Please contact support."
    end
    redirect_to batches_path
  end

  def choose_school
    @school_class = SchoolClass.find_by_id(params[:school_class])
    # @class_sections = @school_class.get_sections_by_name
    @class_sections = @school_class.class_sections.pluck(:section_name, :id)
    respond_to do |format|
      format.js
    end
  end


  private

  def batch_params
    params.require(:batch).permit(:batch_name)
  end

  def class_teacher_params
    params.require(:class_teacher).permit(:class_section_id, :user_id)
  end

  
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_class_section.html.haml
= label_tag 'Choose Sections'
= select_tag 'class_sections', options_for_select(class_sections), class: "form-control", id: "class_sections"

app/views/batches/assign_cls_teacher.html.haml
.container#centerwrap
  .row
    .col-md-10
      %h1 Assign Class Teacher
      = form_for @class_teacher, url: assigned_cls_teacher_batch_path(id: params[:id]), method: :post do |f|
        .row
          .form-group.col-sm-8
            = f.hidden_field :class_section_id, value: @cls_sec.id, class: "form-control"
        .row
          .form-group.col-sm-8
            = f.label :user_id,'Assign Class Teacher'
            = f.select 'user_id', options_from_collection_for_select(@teachers, 'id', 'first_name'), class: "form-control"
        .row
          .col-md-12
            = f.submit "Add Class Teacher", class: "btn btn-primary"

app/views/batches/choose_school.js.haml
$("#section_details").html("#{escape_javascript(render partial: 'class_section', locals: {class_sections: @class_sections}) }");

app/views/batches/edit.html.haml
.container#centerwrap
  %h1 Edit Batch
  = form_for @batch, url: batch_path(id: @batch.id), method: :put do |f|
    .row
      .form-group.col-sm-8
        = f.label :batch_name,'Batch Name'
        = f.text_field :batch_name, class: "form-control"
    .row
      .col-md-12
        = f.submit "Update Batch", class: "btn btn-primary"

app/views/batches/index.html.haml
#centerwrap.container
  .row
    .col-md-10
      %h2{style: "font-weight: bold"} Manage Batches
      = link_to new_batch_path, class: "btn btn-primary", style: "margin-bottom: 10px; float:right;"  do
        %i.glyphicon.glyphicon-plus
        Add Batch
      %table.table.table-striped.table-bordered
        %thead
          %tr.td-font{style: "background-color: #428bca; color: white;"}
            %th Batch Name
            %th Actions
        %tbody
          - @batches.each do |batch|
            %tr
              %td.td-font
                = batch.batch_name
              %td.td-font  
                = link_to edit_batch_path(id: batch.id), class: "btn btn-primary" do
                  %i.glyphicon.glyphicon-pencil
                &nbsp;
                = link_to batch_path(id: batch.id), data:{confirm: "Are you sure,you want to delete this batch?"}, method: :delete, class: "btn btn-primary" do
                  %i.glyphicon.glyphicon-trash
                &nbsp;  
                = link_to batch_path(id: batch.id), method: :get, class: "btn btn-primary" do
                  %i.glyphicon.glyphicon-eye-open  

app/views/batches/new.html.haml
.container#centerwrap
  %h1 Add New Batch
  = form_for @batch, url: batches_path, method: :post do |f|
    .row
      .form-group.col-sm-8
        = f.label :batch_name,'Batch Name'
        = f.text_field :batch_name, class: "form-control"
    .row
      .col-md-12
        = f.submit "Create Batch", class: "btn btn-primary"

app/views/batches/show.html.haml
.container#centerwrap
  .row
    .col-sm-8
      .well
        %h1 Batch #{@batch.batch_name}
        = form_tag choose_school_batches_path, remote: true, method: 'post', id: 'show_classes' do
          .row
            .form-group.col-sm-4
              = label_tag :school_class,'Choose Class'
              = select_tag 'school_class', options_from_collection_for_select(@school_classes, 'id', 'class_name'), class: "form-control"
            .form-group.col-sm-4#section_details
              = label_tag :school_class,'Choose Section'
          .row
            .col-md-12
              = submit_tag("Select Class", class: 'hide', id: 'submit_btn')
        .row#batch-middle
          .col-sm-4
            = link_to "Show Admissions", admissions_path(batch_id: @batch), remote: true, class: 'btn btn-primary', id: "show_admission"
          .col-sm-4
            = link_to "Make New Admission", new_admission_path(batch_id: @batch),  class: 'btn btn-primary', id: "make_admission"
          .col-sm-4
            = link_to "Assign Class Teacher", assign_cls_teacher_batch_path(id: @batch),  class: 'btn btn-primary', id: "assign_class_teacher"  
      .row#admission-details
        .col-sm-8
          %h4 Need to make selections first!
  .row
    .col-sm-8
      .well#student-details    


:javascript
  $('#school_class').change(function() {
    $('#submit_btn').click();
  });

  $("#make_admission").click(function(e) {
    if (!$('#class_sections').length)
    {
      alert("Please select a section first!");
      e.preventDefault();
    }
    else
    {
      var classSectionId = $('#class_sections').val();
      var schoolClassId = $('#school_class').val();
      var newUrl = $(this).attr('href') + "&class_section_id=" + classSectionId + "&school_class_id=" + schoolClassId;
      $(this).attr("href", newUrl);
    }
  });
  $("#show_admission").click(function(e) {
    if (!$('#class_sections').length)
    {
      alert("Please select a section first!");
      e.preventDefault();
    }
    else
    {
      var clsSecId = $('#class_sections').val(); 
      var newUrl = $(this).attr('href') + "&class_section_id=" + clsSecId;
      $(this).attr("href", newUrl);
    }
  });
  $("#assign_class_teacher").click(function(e) {
    if (!$('#class_sections').length)
    {
      alert("Please select a section first!");
      e.preventDefault();
    }
    else
    {
      var clsSecId = $('#class_sections').val();
      var schoolClassId = $('#school_class').val();
      var newUrl = $(this).attr('href') + "?class_section_id=" + clsSecId + "&school_class_id=" + schoolClassId;
      $(this).attr("href", newUrl);
    }
  });