config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users

  devise_scope :user do
    authenticated do
      root 'schools#dashboard', as: :authenticated_root
    end
    
    root to: "devise/sessions#new"
  end
  
  resources :users, except: :create do
    collection do
      post 'registration'
      post 'create_user'
    end
    member do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :schools do
    member do
      get 'edit_profile'
      post 'update_profile'
    end
  end

  resources :batches do
    collection do
      post 'choose_school'
    end
    member do
      get 'assign_cls_teacher'
      post 'assigned_cls_teacher'
    end 
  end

  resources :school_classes
  resources :class_sections
  resources :admissions
  resources :class_teachers
  resources :exams
  resources :question_papers
  resources :customer_registrations

end

app/models/admission.rb
class Admission < ApplicationRecord
  before_save :create_admission_no	
  belongs_to :batch
  belongs_to :student
  belongs_to :class_section

  def create_admission_no
  	self.admission_number = rand(1000000)
  end

end

app/controllers/admissions_controller.rb
class AdmissionsController < ApplicationController

  layout "dashboard"

  def index
    @batch = Batch.find_by(id: params[:batch_id])
    @class_section = ClassSection.find_by_id(params[:class_section_id])
    @admissions = Admission.where(class_section_id: @class_section.id, batch_id: @batch.id)
    respond_to do |format|
      format.js
    end
  end

  def new
    @school_class = SchoolClass.find_by_id(params[:school_class_id])
    @admission = Admission.new
    @batch = Batch.find_by(id: params[:batch_id])
    @class_section = ClassSection.find_by_id(params[:class_section_id])
  end

  def create
    student = Student.create(admission_params[:student])
    admission = Admission.new(admission_params.except(:student))
    admission.batch_id = params[:batch_id]
    admission.class_section_id = params[:class_section_id]
    admission.student_id = student.id
    if admission.save!
      flash[:success] = "Admission done successfully."
    else
      flash[:danger] = "Something went wrong."  
    end
    redirect_to batch_path(id: params[:batch_id])
  end

  def destroy
    @batch = Batch.find_by(id: params[:batch_id])
    @class_section = ClassSection.find_by_id(params[:class_section_id])
    @admissions = Admission.where(class_section_id: @class_section.id, batch_id: @batch.id)
    admission = Admission.find_by(id: params[:id])
    if admission.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  def edit
    @admission = Admission.find_by(id: params[:id])
  end

  def update
    @admission = Admission.find_by(id: params[:id])
    if @admission.update_attributes(admission_params.except(:student))
      student = @admission.student
      student.update_attributes(admission_params[:student])
      flash[:success] = "Sucessfully updated!!"
    else
      flash[:error] = "Sorry! Something went wrong. Please contact support."
    end
    redirect_to batch_path(id: @admission.batch_id)
  end

  private

  def admission_params
    params.require(:admission).permit(:roll_no, student: [:name, :email, :gender, :dob, :father_name,
      :mother_name, :contact_no, :address, :country])
  end


end

app/helpers/admissions_helper.rb
module AdmissionsHelper

  def select_country_for_student
    [['INDIA', 'india'], ['USA', 'usa' ], ['UK', 'uk']]   
  end

  def country_label(country)
    case country
    when "INDIA"
      "DESI student"
    when "USA"
      "US student"
    else
      "UK student"
    end
  end

end

app/views/admissions/_index.html.haml
#msg-show
%table.table.table-striped.table-bordered
  %thead
    %tr.td-font.td-fix{style: "background-color: #428bca; color: white;"}
      %th Roll No
      %th Admission Number
      %th Student Name
      %th Email
      %th Gender
      %th Contact No
      %th Address
      %th Father Name
      %th Mother Name
      %th Country
      %th Actions
  %tbody
    - if admissions.present?
      - admissions.each do |admission|
        - student = admission.student
        %tr
          %td.td-font.td-fix
            = admission.roll_no
          %td.td-font.td-fix
            = admission.admission_number    
          %td.td-font.td-fix
            = student.name
            &nbsp;
            %span.label{class: "label-danger"}
              = country_label(student.country)
            - if student.country == "USA" || student.country == "UK"
              %span.label{class: "label-primary"} Hostel
          %td.td-font.td-fix
            = student.email
          %td.td-font.td-fix
            = student.gender
          %td.td-font.td-fix
            = ("*" * 6) + student.contact_no[student.contact_no.length - 4 ,4] if student.contact_no.present?
          %td.td-font.td-fix
            = student.address
          %td.td-font.td-fix
            = student.father_name 
          %td.td-font.td-fix
            = student.mother_name
          %td.td-font.td-fix
            = student.country.upcase
          %td.td-font.td-fix
            = link_to edit_admission_path(id: admission.id), class: "btn btn-primary" do
              %i.glyphicon.glyphicon-pencil
            &nbsp;
            &nbsp;
            = link_to admission_path(id: admission.id, batch_id: admission.batch_id, class_section_id: admission.class_section_id), remote: true, data:{confirm: "Are you sure,you want to delete this admission?"}, method: :delete, class: "btn btn-primary" do
              %i.glyphicon.glyphicon-trash
    - else
      %tr
        %td.td-font.td-fix{colspan: "8"}
          No Record found

app/views/admissions/destroy.js.haml
$("#student-details").html("#{escape_javascript(render partial: 'index', locals: {admissions: @admissions}) }");
$("#msg-show").html("<div class='alert alert-success' role='alert'>Admission has been deleted successfully.</div>");

app/views/admissions/edit.html.haml
.container#centerwrap
  .row
    .col-sm-8
      %h1 Edit Admission
      = form_for @admission, url: admission_path(id: @admission.id), method: :put do |f|
        .row
          .form-group.col-sm-8
            = f.label :roll_no,'Roll Number'
            = f.text_field :roll_no, class: "form-control"
        = f.fields_for @admission.student do |s|    
          .row
            .form-group.col-sm-8
              = s.label :name,'Student Name'
              = s.text_field :name, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :email,'Student Email'
              = s.text_field :email, class: "form-control"
          .row
            .form-group.col-sm-2
              = s.radio_button :gender, 'Male'
              = s.label :gender, "Male"
            .form-group.col-sm-2 
              = s.radio_button :gender, 'female'
              = s.label :gender, "Female"
          .row
            .form-group.col-sm-8
              = s.label :dob,'DOB'
              = s.text_field :dob, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :father_name,'Father Name'
              = s.text_field :father_name, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :mother_name,'Mother Name'
              = s.text_field :mother_name, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :contact_no,'Contact no'
              = s.text_field :contact_no, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :address,'Address'
              = s.text_field :address, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :country,'Seletct Country'
              = s.select :country, select_country_for_student, class: "form-control"  
        .row
          .col-md-12
            = f.submit "Update Admission", class: "btn btn-primary"

app/views/admissions/index.js.haml
$("#student-details").html("#{escape_javascript(render partial: 'index', locals: {admissions: @admissions}) }");

app/views/admissions/new.html.haml
.container#centerwrap
  .row
    .col-sm-8
      %h1 Add New Admission
      = form_for @admission, url: admissions_path(school_class_id: @school_class.id, batch_id: @batch.id, class_section_id: @class_section.id), method: :post do |f|
        .row
          .form-group.col-sm-8
            = f.label :roll_no,'Roll Number'
            = f.text_field :roll_no, class: "form-control"
        = f.fields_for :student do |s|    
          .row
            .form-group.col-sm-8
              = s.label :name,'Student Name'
              = s.text_field :name, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :email,'Student Email'
              = s.text_field :email, class: "form-control"
          .row
            .form-group.col-sm-2
              = s.radio_button :gender, 'Male'
              = s.label :gender, "Male"
            .form-group.col-sm-2 
              = s.radio_button :gender, 'female'
              = s.label :gender, "Female"
          .row
            .form-group.col-sm-8
              = s.label :dob,'DOB'
              = s.text_field :dob, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :father_name,'Father Name'
              = s.text_field :father_name, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :mother_name,'Mother Name'
              = s.text_field :mother_name, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :contact_no,'Contact no'
              = s.text_field :contact_no, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :address,'Address'
              = s.text_field :address, class: "form-control"
          .row
            .form-group.col-sm-8
              = s.label :country,'Seletct Country'
              = s.select :country, select_country_for_student, class: "form-control"  
        .row
          .col-md-12
            = f.submit "Create Admission", class: "btn btn-primary"