config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users

  devise_scope :user do
    authenticated do
      root 'schools#dashboard', as: :authenticated_root
    end
    
    root to: "devise/sessions#new"
  end
  
  resources :users, except: :create do
    collection do
      post 'registration'
      post 'create_user'
    end
    member do
      get 'edit_password'
      patch 'update_password'
    end
  end

  resources :schools do
    member do
      get 'edit_profile'
      post 'update_profile'
    end
  end

  resources :batches do
    collection do
      post 'choose_school'
    end
    member do
      get 'assign_cls_teacher'
      post 'assigned_cls_teacher'
    end 
  end

  resources :school_classes
  resources :class_sections
  resources :admissions
  resources :class_teachers
  resources :exams
  resources :question_papers
  resources :customer_registrations

end

app/models/admission.rb
class Admission < ApplicationRecord
  before_save :create_admission_no	
  belongs_to :batch
  belongs_to :student
  belongs_to :class_section

  def create_admission_no
  	self.admission_number = rand(1000000)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
class Batch < ApplicationRecord
  has_many :admissions
  has_many :students, through: :admissions
end

app/models/class_section.rb
class ClassSection < ApplicationRecord

  belongs_to :school_class

  # def get_user_by_role
  #   sections = ""
  #   self.class_sections.each do |sec|
  #     sections = [sections, sec.section_name].join(' ')
  #   end
  #   sections
  # end
  
end

app/models/class_teacher.rb
class ClassTeacher < ApplicationRecord
  # attr_accessor :batch_id
end

app/models/customer_registration.rb
class CustomerRegistration < ApplicationRecord

  validates_presence_of :email, :first_name
  validates_uniqueness_of :email

  enum source_of_hearing: [:tv, :facebook, :mobile_advertisement, :newspaper]
  enum hobby: [:games, :movies, :singing, :dancing, :reading]

  def country_name
    c = ISO3166::Country[self.country]
    c.try(:name)
  end
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :question_papers


end

app/models/question_paper.rb
class QuestionPaper < ApplicationRecord
  belongs_to :exam
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/school.rb
class School < ApplicationRecord
  validates :school_name, presence: true
  resourcify

  has_many :users
  has_many :school_classes
end

app/models/school_class.rb
class SchoolClass < ApplicationRecord
  belongs_to :school
  has_many :class_sections

  def get_sections_by_name
    sections = ""
    self.class_sections.each do |sec|
      sections = [sections, sec.section_name].join(' ')
    end
    sections
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :admissions, dependent: :destroy
  has_many :batches, through: :admissions
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :school

  attr_accessor :school_name, :school_role, :full_name

  def full_name
  	[self.first_name, self.last_name].join(' ')
  end
  
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  layout "dashboard"

  def index
    @exams = Exam.all
  end

  def new
    @exam = Exam.new
    @school_classes = current_user.school.school_classes
    @batches = Batch.all
  end

  def create
    exam = Exam.new(exam_params)
    if exam.save!
      flash[:success] = "Exam Added successfully."
    else
      flash[:danger] = "Something went wrong."  
    end
    redirect_to exams_path
  end

  private

  def exam_params
    params.require(:exam).permit(:exam_name, :subject, :school_class_id, :batch_id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # layout "application"
  layout :resolve_layout
  
  def registration
    user = User.new(registration_params)
    create_school_for_user(user)
    if user.save
      user.add_role :admin
      flash[:success] = "Sucessfully Registered!!"
    else
      flash[:error] = "Sorry! Something went wrong. Please contact support."
    end
    redirect_to root_path
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Sucessfully updated!!"
    else
      flash[:error] = "Sorry! Something went wrong. Please contact support."
    end
    redirect_to school_path(id: @user.school_id)
  end

  def new
    @user = User.new
  end

  def create_user
    user = User.new(user_params)
    user.password = "Chetu@123"
    user.password_confirmation = "Chetu@123"
    user.school_id = current_user.school_id
    if user.save!
      user.add_role params[:user][:school_role].to_sym
      flash[:success] = "User Added successfully."
    else
      flash[:danger] = "Something went wrong."  
    end
    redirect_to users_path
  end

  def edit_password
    @user =  current_user
    
    respond_to do |format|
      format.js
    end
  end

  def update_password
    @user =  current_user
    if @user.update_attributes(password_params)
      bypass_sign_in(@user)
      flash[:success] = "Sucessfully updated!!"
    else
      flash[:error] = "Sorry! Something went wrong. Please contact support."
    end
    redirect_to root_path
  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find_by(id: params[:id])
    if @user.destroy
      flash[:danger] = "User has been deleted successfully."
    end
    redirect_to users_path
  end

  private

  def create_school_for_user(user)
    school = School.create(school_name: params[:user][:school_name])
    user.school_id = school.id
  end

  def registration_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                :phone, :password, :password_confirmation, :school_name)
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :phone, :details)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def resolve_layout
    case action_name
    when "edit", "edit_password", "index", "new"
      "dashboard"
    else
      "application"
    end
  end

end

app/helpers/admissions_helper.rb
module AdmissionsHelper

  def select_country_for_student
    [['INDIA', 'india'], ['USA', 'usa' ], ['UK', 'uk']]   
  end

  def country_label(country)
    case country
    when "INDIA"
      "DESI student"
    when "USA"
      "US student"
    else
      "UK student"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/class_sections_helper.rb
module ClassSectionsHelper

end

app/helpers/class_teachers_helper.rb
module ClassTeachersHelper

  def get_user_teacher(cls)
    role = ''
    school = cls.school
    school.users.each do |user|
      role = user.roles.first.name
    end
    role
  end

end

app/helpers/exams_helper.rb
module ExamsHelper

  def get_class_name(class_id)
    school_class = ' '
    school_class = SchoolClass.find_by_id(class_id).class_name
  end

  def get_batch_name(batch_id)
    batch_name = ' '
    batch_name = Batch.find_by_id(batch_id).batch_name
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def prepare_user_roles
    [['ADMIN', 'admin'], ['PRINCIPAL', 'principal' ], ['TEACHER', 'teacher']]  
  end

  def user_role(user)
  	user.roles.first.name.upcase
  end
end

app/views/exams/index.html.haml
#centerwrap.container
  .row
    .col-md-10
      %h2{style: "font-weight: bold"} Manage Exams
      = link_to new_exam_path, class: "btn btn-primary", style: "margin-bottom: 10px; float:right;"  do
        %i.glyphicon.glyphicon-plus
        Add Exam
      %table.table.table-striped.table-bordered
        %thead
          %tr.td-font{style: "background-color: #428bca; color: white;"}
            %th Exam Name
            %th Subject Name
            %th Class Name
            %th Batch Name
            %th Actions
        %tbody
          - @exams.each do |exam|
            %tr
              %td.td-font
                = exam.exam_name
              %td.td-font
                = exam.subject
              %td.td-font
                = get_class_name(exam.school_class_id)
              %td.td-font
                = get_batch_name(exam.batch_id)     
              %td.td-font  
                = link_to edit_exam_path(id: exam.id), class: "btn btn-primary" do
                  %i.glyphicon.glyphicon-pencil
                &nbsp;
                = link_to exam_path(id: exam.id), data:{confirm: "Are you sure,you want to delete this exam?"}, method: :delete, class: "btn btn-primary" do
                  %i.glyphicon.glyphicon-trash
                &nbsp;  
                = link_to question_papers_path(id: exam.id), method: :get, class: "btn btn-primary" do
                  %i.glyphicon.glyphicon-eye-open  

app/views/exams/new.html.haml
.container#centerwrap
  %h1 Add New Exam
  = form_for @exam, url: exams_path, method: :post do |f|
    .row
      .form-group.col-sm-8
        = f.label :exam_name,'Exam Name'
        = f.text_field :exam_name, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :subject,'Subject'
        = f.text_field :subject, class: "form-control"
    .row
      .form-group.col-sm-4
        = f.label :school_class_id,'Assign Class'
        = f.select 'school_class_id', options_from_collection_for_select(@school_classes, 'id', 'class_name'), class: "form-control"
    .row
      .form-group.col-sm-4
        = f.label :batch_id,'Batch Name'
        = f.select 'batch_id', options_from_collection_for_select(@batches, 'id', 'batch_name'), class: "form-control"         
    .row
      .col-md-12
        = f.submit "Create Exam", class: "btn btn-primary"

app/views/users/_edit_pwd_form.html.haml
%h1 Change Your Password
= form_for user, url: update_password_user_path(id: user.id), method: :patch do |f|
  .row
    .form-group.col-sm-8
      = f.label :password,'New Password'
      %br
      = f.password_field :password, autocomplete: "off" , class: "form-control"
  .row
    .form-group.col-sm-8
      = f.label :password_confirmation,'Password Confirmation'
      %br
      = f.password_field :password_confirmation, class: "form-control"
  .row
    .col-md-12
      = f.submit "Change Password", class: "btn btn-primary"

app/views/users/edit.html.haml
.container#centerwrap
  %h1 Edit User Profile
  = form_for @user, url: user_path(id: @user.id), method: :patch do |f|
    .row
      .form-group.col-sm-8
        = f.label :email,'Email'
        = f.text_field :email, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :first_name,'First Name'
        = f.text_field :first_name, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :last_name,'Last Name'
        = f.text_field :last_name, class: "form-control"
    .row
      .col-md-12
        = f.submit "Update Profile", class: "btn btn-primary"

app/views/users/edit_password.js.haml
$("#personal_details").html("#{escape_javascript(render partial: 'edit_pwd_form', locals: { user: @user } ) }");

app/views/users/index.html.haml
#centerwrap.container
  .row
    .col-md-10
      %h2{style: "font-weight: bold"} Manage Users
      = link_to new_user_path, class: "btn btn-primary", style: "margin-bottom: 10px; float:right;"  do
        %i.glyphicon.glyphicon-plus
        Add User
      %table.table.table-striped.table-bordered
        %thead
          %tr.td-font{style: "background-color: #428bca; color: white;"}
            %th Name
            %th Email
            %th Contact
            %th Details
            %th Actions
        %tbody
          - @users.each do |user|
            %tr
              %td.td-font
                = user.full_name.titleize
                &nbsp;
                %span.label{class: (user.has_role? :admin) ? "label-danger" : "label-primary"}
                  = user_role(user)
              %td.td-font= user.email  
              %td.td-font= user.phone
              %td.td-font= user.details
              %td.td-font
                - unless user.has_role? :admin
                  = link_to edit_user_path(id: user.id), class: "btn btn-primary" do
                    %i.glyphicon.glyphicon-pencil
                  &nbsp;
                  = link_to user_path(id: user.id), data:{confirm: "Are you sure,you want to delete this user?"}, method: :delete, class: "btn btn-primary" do
                    %i.glyphicon.glyphicon-trash

app/views/users/new.html.haml
.container#centerwrap
  %h1 Add New User
  = form_for @user, url: create_user_users_path, method: :post do |f|
    .row
      .form-group.col-sm-8
        = f.label :email,'Email'
        = f.text_field :email, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :first_name,'First Name'
        = f.text_field :first_name, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :last_name,'Last Name'
        = f.text_field :last_name, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :phone,'Contact'
        = f.text_field :phone, class: "form-control" 
    .row
      .form-group.col-sm-8
        = f.label :details,'Description'
        = f.text_field :details, class: "form-control"
    .row
      .form-group.col-sm-8
        = f.label :school_role,'Choose Role'
        = f.select :school_role, prepare_user_roles, class: "form-control"  
    .row
      .col-md-12
        = f.submit "Create User", class: "btn btn-primary"